# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_markdown_insert_content_extension
project_short_description: Jupyterlab extension to automatically insert content into
    markdown - such as TOC, bibliography, list of figures etc.
python_name: jupyterlab_markdown_insert_content_extension
repository: ''
test: true

